# Site settings
title:          Nathan Minchow Blog
description:    "Random musings and things"
url:            "https://nspenner.github.com"

# Author
author:
  name:         Nathan Minchow
  url:          https://nminchow.com
  email:        nathan.minchow@outlook.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

remote-theme: chesterhow/tale
